/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Auto-generated code. Do not edit.

using System.Text.Json.Serialization;
using System.Collections.Generic;
using System.Text.Json;

namespace Google.GenAI.Types {
  /// <summary>
  /// Output only. The reason why the model stopped generating tokens.  If empty, the model has not
  /// stopped generating the tokens.
  /// </summary>

  [JsonConverter(typeof(FinishReasonConverter))]
  public readonly record struct FinishReason : IEquatable<FinishReason> {
    public string Value { get; }

    private FinishReason(string value) {
      Value = value;
    }

    /// <summary>
    /// The finish reason is unspecified.
    /// </summary>
    public static FinishReason FinishReasonUnspecified { get; } = new("FINISH_REASON_UNSPECIFIED");

    /// <summary>
    /// Token generation reached a natural stopping point or a configured stop sequence.
    /// </summary>
    public static FinishReason Stop { get; } = new("STOP");

    /// <summary>
    /// Token generation reached the configured maximum output tokens.
    /// </summary>
    public static FinishReason MaxTokens { get; } = new("MAX_TOKENS");

    /// <summary>
    /// Token generation stopped because the content potentially contains safety violations. NOTE:
    /// When streaming, [content][] is empty if content filters blocks the output.
    /// </summary>
    public static FinishReason Safety { get; } = new("SAFETY");

    /// <summary>
    /// The token generation stopped because of potential recitation.
    /// </summary>
    public static FinishReason Recitation { get; } = new("RECITATION");

    /// <summary>
    /// The token generation stopped because of using an unsupported language.
    /// </summary>
    public static FinishReason Language { get; } = new("LANGUAGE");

    /// <summary>
    /// All other reasons that stopped the token generation.
    /// </summary>
    public static FinishReason Other { get; } = new("OTHER");

    /// <summary>
    /// Token generation stopped because the content contains forbidden terms.
    /// </summary>
    public static FinishReason Blocklist { get; } = new("BLOCKLIST");

    /// <summary>
    /// Token generation stopped for potentially containing prohibited content.
    /// </summary>
    public static FinishReason ProhibitedContent { get; } = new("PROHIBITED_CONTENT");

    /// <summary>
    /// Token generation stopped because the content potentially contains Sensitive Personally
    /// Identifiable Information (SPII).
    /// </summary>
    public static FinishReason Spii { get; } = new("SPII");

    /// <summary>
    /// The function call generated by the model is invalid.
    /// </summary>
    public static FinishReason MalformedFunctionCall { get; } = new("MALFORMED_FUNCTION_CALL");

    /// <summary>
    /// Token generation stopped because generated images have safety violations.
    /// </summary>
    public static FinishReason ImageSafety { get; } = new("IMAGE_SAFETY");

    /// <summary>
    /// The tool call generated by the model is invalid.
    /// </summary>
    public static FinishReason UnexpectedToolCall { get; } = new("UNEXPECTED_TOOL_CALL");

    /// <summary>
    /// Model called too many tools consecutively, thus the system exited execution.
    /// </summary>
    public static FinishReason TooManyToolCalls { get; } = new("TOO_MANY_TOOL_CALLS");

    /// <summary>
    /// Image generation stopped because the generated images have prohibited content.
    /// </summary>
    public static FinishReason ImageProhibitedContent { get; } = new("IMAGE_PROHIBITED_CONTENT");

    /// <summary>
    /// The model was expected to generate an image, but none was generated.
    /// </summary>
    public static FinishReason NoImage { get; } = new("NO_IMAGE");

    /// <summary>
    /// Image generation stopped because the generated image may be a recitation from a source.
    /// </summary>
    public static FinishReason ImageRecitation { get; } = new("IMAGE_RECITATION");

    /// <summary>
    /// Image generation stopped for a reason not otherwise specified.
    /// </summary>
    public static FinishReason ImageOther { get; } = new("IMAGE_OTHER");

    /// <summary>
    /// Token generation stopped because the response reached the per-request token limit, but
    /// generation is not yet complete. The response can be continued by passing the returned
    /// `continuation_token` in a subsequent request.
    /// </summary>
    public static FinishReason Continuation { get; } = new("CONTINUATION");

    public static IReadOnlyList<FinishReason> AllValues {
      get;
    } = new[] { FinishReasonUnspecified,
                Stop,
                MaxTokens,
                Safety,
                Recitation,
                Language,
                Other,
                Blocklist,
                ProhibitedContent,
                Spii,
                MalformedFunctionCall,
                ImageSafety,
                UnexpectedToolCall,
                TooManyToolCalls,
                ImageProhibitedContent,
                NoImage,
                ImageRecitation,
                ImageOther,
                Continuation };

    public static FinishReason FromString(string value) {
      if (string.IsNullOrEmpty(value)) {
        return new FinishReason("FINISH_REASON_UNSPECIFIED");
      }

      foreach (var known in AllValues) {
        if (known.Value == value) {
          return known;
        }
      }

      return new FinishReason(value);
    }

    public override string ToString() => Value ?? string.Empty;

    public static implicit operator FinishReason(string value) => FromString(value);

    public bool Equals(FinishReason other) => Value == other.Value;

    public override int GetHashCode() => Value?.GetHashCode() ?? 0;
  }

  public class FinishReasonConverter : JsonConverter<FinishReason> {
    public override FinishReason Read(ref Utf8JsonReader reader, System.Type typeToConvert,
                                      JsonSerializerOptions options) {
      var value = reader.GetString();
      return FinishReason.FromString(value);
    }

    public override void Write(Utf8JsonWriter writer, FinishReason value,
                               JsonSerializerOptions options) {
      writer.WriteStringValue(value.Value);
    }
  }
}
