/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Auto-generated code. Do not edit.

using System.Text.Json.Serialization;

namespace Google.GenAI.Types {
  /// <summary>
  /// Output only. The reason why the model stopped generating tokens.   If empty, the model has not
  /// stopped generating the tokens.
  /// </summary>
  [JsonConverter(typeof(JsonStringEnumConverter<FinishReason>))]
  public enum FinishReason {
    /// <summary>
    /// The finish reason is unspecified.
    /// </summary>
    [JsonPropertyName("FINISH_REASON_UNSPECIFIED")] FINISH_REASON_UNSPECIFIED,

    /// <summary>
    /// Token generation reached a natural stopping point or a configured stop sequence.
    /// </summary>
    [JsonPropertyName("STOP")] STOP,

    /// <summary>
    /// Token generation reached the configured maximum output tokens.
    /// </summary>
    [JsonPropertyName("MAX_TOKENS")] MAX_TOKENS,

    /// <summary>
    /// Token generation stopped because the content potentially contains safety violations. NOTE:
    /// When streaming, [content][] is empty if content filters blocks the output.
    /// </summary>
    [JsonPropertyName("SAFETY")] SAFETY,

    /// <summary>
    /// The token generation stopped because of potential recitation.
    /// </summary>
    [JsonPropertyName("RECITATION")] RECITATION,

    /// <summary>
    /// The token generation stopped because of using an unsupported language.
    /// </summary>
    [JsonPropertyName("LANGUAGE")] LANGUAGE,

    /// <summary>
    /// All other reasons that stopped the token generation.
    /// </summary>
    [JsonPropertyName("OTHER")] OTHER,

    /// <summary>
    /// Token generation stopped because the content contains forbidden terms.
    /// </summary>
    [JsonPropertyName("BLOCKLIST")] BLOCKLIST,

    /// <summary>
    /// Token generation stopped for potentially containing prohibited content.
    /// </summary>
    [JsonPropertyName("PROHIBITED_CONTENT")] PROHIBITED_CONTENT,

    /// <summary>
    /// Token generation stopped because the content potentially contains Sensitive Personally
    /// Identifiable Information (SPII).
    /// </summary>
    [JsonPropertyName("SPII")] SPII,

    /// <summary>
    /// The function call generated by the model is invalid.
    /// </summary>
    [JsonPropertyName("MALFORMED_FUNCTION_CALL")] MALFORMED_FUNCTION_CALL,

    /// <summary>
    /// Token generation stopped because generated images have safety violations.
    /// </summary>
    [JsonPropertyName("IMAGE_SAFETY")] IMAGE_SAFETY,

    /// <summary>
    /// The tool call generated by the model is invalid.
    /// </summary>
    [JsonPropertyName("UNEXPECTED_TOOL_CALL")] UNEXPECTED_TOOL_CALL,

    /// <summary>
    /// Image generation stopped because the generated images have prohibited content.
    /// </summary>
    [JsonPropertyName("IMAGE_PROHIBITED_CONTENT")] IMAGE_PROHIBITED_CONTENT
  }
}
