/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Auto-generated code. Do not edit.

using System.Text.Json.Serialization;

namespace Google.GenAI.Types {
  /// <summary>
  /// The reason why the turn is complete.
  /// </summary>
  [JsonConverter(typeof(JsonStringEnumConverter<TurnCompleteReason>))]
  public enum TurnCompleteReason {
    /// <summary>
    /// Default value. Reason is unspecified.
    /// </summary>
    [JsonPropertyName("TURN_COMPLETE_REASON_UNSPECIFIED")] TURN_COMPLETE_REASON_UNSPECIFIED,

    /// <summary>
    /// The function call generated by the model is invalid.
    /// </summary>
    [JsonPropertyName("MALFORMED_FUNCTION_CALL")] MALFORMED_FUNCTION_CALL,

    /// <summary>
    /// The response is rejected by the model.
    /// </summary>
    [JsonPropertyName("RESPONSE_REJECTED")] RESPONSE_REJECTED,

    /// <summary>
    /// Needs more input from the user.
    /// </summary>
    [JsonPropertyName("NEED_MORE_INPUT")] NEED_MORE_INPUT
  }
}
